[build]
  publish = "dist/"
  command = "npm run build"

[context.deploy-preview]
  publish = "dist/"

[[redirects]]
  from = "/guides"
  to = "/guides/overview/why-cypress/"
  status = 301
  force = true

[[redirects]]
  from = "/api/"
  to = "/api/table-of-contents/"
  status = 301
  force = true

[[redirects]]
  from = "/api/api/table-of-contents"
  to = "/api/table-of-contents/"
  status = 301
  force = true

[[redirects]]
  from = "/api/events/catalog-of-events"
  to = "/api/cypress-api/catalog-of-events"
  status = 301
  force = true

[[redirects]]
  from = "/plugins/directory"
  to = "/app/plugins/plugins-list"
  status = 301
  force = true

[[redirects]]
  from = "/examples"
  to = "/app/references/recipes/"
  status = 301
  force = true

[[redirects]]
  from = "/examples/examples"
  to = "/app/references/recipes/"
  status = 301
  force = true

[[redirects]]
  from = "/examples/app/references/recipes"
  to = "/app/references/recipes/"
  status = 301
  force = true

[[redirects]]
  from = "/examples/app/continuous-integration/docker"
  to = "/app/continuous-integration/docker"
  status = 301
  force = true

[[redirects]]
  from = "/faq"
  to = "/app/faq/"
  status = 301
  force = true

[[redirects]]
  from = "/guides/overview/choosing-testing-type"
  to = "/guides/core-concepts/testing-types/"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/dashboard-introduction"
  to = "/guides/dashboard/introduction/"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing"
  to = "/app/component-testing/get-started"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/introduction"
  to = "/app/component-testing/get-started"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/writing-your-first-component-test"
  to = "/app/component-testing/get-started"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/framework-configuration"
  to = "/guides/component-testing/component-framework-configuration/"
  status = 301
  force = true

[[redirects]]
  from = "/guides/core-concepts/test-runner"
  to = "/guides/core-concepts/open-mode"
  status = 301
  force = true

[[redirects]]
  from = "/guides/core-concepts/cypress-studio"
  to = "/guides/guides/cypress-studio"
  status = 301
  force = true

[[redirects]]
  from = "/guides/getting-started/writing-your-first-test"
  to = "/guides/end-to-end-testing/writing-your-first-end-to-end-test"
  status = 301
  force = true

[[redirects]]
  from = "/guides/getting-started/testing-your-app"
  to = "/guides/end-to-end-testing/testing-your-app"
  status = 301
  force = true

[[redirects]]
  from = "/guides/getting-started/component-testing"
  to = "/app/component-testing/get-started"
  status = 301
  force = true

[[redirects]]
  from = "/guides/testing-strategies/auth0-authentication"
  to = "/app/guides/authentication-testing/auth0-authentication"
  status = 301
  force = true

[[redirects]]
  from = "/guides/testing-strategies/amazon-cognito-authentication"
  to = "/app/guides/authentication-testing/amazon-cognito-authentication"
  status = 301
  force = true

[[redirects]]
  from = "/guides/testing-strategies/okta-authentication"
  to = "/app/guides/authentication-testing/okta-authentication"
  status = 301
  force = true

[[redirects]]
  from = "/guides/testing-strategies/google-authentication"
  to = "/app/guides/authentication-testing/google-authentication"
  status = 301
  force = true

[[redirects]]
  from = "/guides/testing-strategies/working-with-graphql"
  to = "/app/guides/network-requests"
  status = 301
  force = true

[[redirects]]
  from = "/guides/migrating-to-cypress/protractor"
  to = "/app/guides/migration/protractor-to-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/guides/migrating-to-cypress/selenium"
  to = "/app/guides/migration/selenium-to-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/guides/references/bundled-tools"
  to = "/guides/references/bundled-libraries"
  status = 301
  force = true

[[redirects]]
  from = "/guides/references/bundled-tools.html"
  to = "/guides/references/bundled-libraries"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/quickstart-react"
  to = "/guides/component-testing/react/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/mounting-react"
  to = "/guides/component-testing/react/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/testing-react"
  to = "/guides/component-testing/react/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/events-react"
  to = "/guides/component-testing/react/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/custom-mount-react"
  to = "/guides/component-testing/react/examples"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/quickstart-angular"
  to = "/guides/component-testing/angular/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/mounting-angular"
  to = "/guides/component-testing/angular/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/testing-angular"
  to = "/guides/component-testing/angular/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/events-angular"
  to = "/guides/component-testing/angular/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/custom-mount-angular"
  to = "/guides/component-testing/angular/examples"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/slots-angular"
  to = "/guides/component-testing/angular/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/quickstart-vue"
  to = "/guides/component-testing/vue/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/mounting-vue"
  to = "/guides/component-testing/vue/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/testing-vue"
  to = "/guides/component-testing/vue/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/events-vue"
  to = "/guides/component-testing/vue/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/custom-mount-vue"
  to = "/guides/component-testing/vue/examples"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/slots-vue"
  to = "/guides/component-testing/vue/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/quickstart-svelte"
  to = "/guides/component-testing/svelte/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/mounting-svelte"
  to = "/guides/component-testing/svelte/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/testing-svelte"
  to = "/guides/component-testing/svelte/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/events-svelte"
  to = "/guides/component-testing/svelte/quickstart"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/custom-mount-svelte"
  to = "/guides/component-testing/svelte/examples"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/component-test-troubleshooting"
  to = "/app/faq"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/analytics"
  to = "/guides/cloud/features/analytics/overview"
  status = 301
  force = true

 [[redirects]]
  from = "/guides/cloud/features/analytics"
  to = "/guides/cloud/features/analytics/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/flaky-test-management"
  to = "/guides/cloud/features/flaky-test-management"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/flaky-test-management"
  to = "/guides/cloud/features/flaky-test-management"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/introduction"
  to = "/guides/cloud/get-started/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/github-integration"
  to = "/guides/cloud/integrations/github"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/github-integration"
  to = "/guides/cloud/integrations/github"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/gitlab-integration"
  to = "/guides/cloud/integrations/gitlab"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/gitlab-integration"
  to = "/guides/cloud/integrations/gitlab"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/jira-integration"
  to = "/guides/cloud/integrations/jira"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/jira-integration"
  to = "/guides/cloud/integrations/jira"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/slack-integration"
  to = "/guides/cloud/integrations/slack"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/slack-integration"
  to = "/guides/cloud/integrations/slack"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/bitbucket-integration"
  to = "/guides/cloud/integrations/bitbucket"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/bitbucket-integration"
  to = "/guides/cloud/integrations/bitbucket"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/organizations"
  to = "/guides/cloud/organizations"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/projects"
  to = "/guides/cloud/projects"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/runs"
  to = "/guides/cloud/runs"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/smart-orchestration"
  to = "/guides/cloud/features/smart-orchestration"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/users"
  to = "/guides/cloud/users"
  status = 301
  force = true

[[redirects]]
  from = "/faq/questions/dashboard-faq"
  to = "/cloud/faq"
  status = 301
  force = true

# New Cloud IA (Summer 2023)

[[redirects]]
  from = "/guides/cloud/projects"
  to = "/guides/cloud/account-management/projects"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/organizations"
  to = "/guides/cloud/account-management/organizations"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/users"
  to = "/guides/cloud/account-management/users"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/features/smart-orchestration"
  to = "/guides/cloud/features/smart-orchestration/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/guides/parallelization"
  to = "/guides/cloud/features/smart-orchestration/parallelization"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/runs"
  to = "/guides/cloud/features/recorded-runs"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/integrations/github"
  to = "/guides/cloud/integrations/source-control/github"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/integrations/gitlab"
  to = "/guides/cloud/integrations/source-control/gitlab"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/integrations/bitbucket"
  to = "/guides/cloud/integrations/source-control/bitbucket"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/debugging/test-replay"
  to = "/guides/cloud/features/test-replay"
  status = 301
  force = true

[[redirects]]
  from = "/guides/cloud/debugging/recorded-runs"
  to = "/guides/cloud/features/recorded-runs"
  status = 301
  force = true

[[redirects]]
  from = "/api/commands"
  to = "/api/table-of-contents"
  status = 301
  force = true

[[redirects]]
  from = "/api/commands/"
  to = "/api/table-of-contents"
  status = 301
  force = true

[[redirects]]
  from = "/api/commands/route"
  to = "/api/commands/intercept"
  status = 301
  force = true

[[redirects]]
  from = "/api/commands/route2"
  to = "/api/commands/intercept"
  status = 301
  force = true

[[redirects]]
  from = "/api/commands/server"
  to = "/api/commands/intercept"
  status = 301
  force = true

[[redirects]]
  from = "/api/cypress-api/cypress-server"
  to = "/api/commands/intercept"
  status = 301
  force = true

[[redirects]]
  from = "/api/cypress-api/guides/component-testing/introduction"
  to = "/app/component-testing/get-started"
  status = 301
  force = true

[[redirects]]
  from = "/api/introduction/api"
  to = "/api/table-of-contents"
  status = 301
  force = true

[[redirects]]
  from = "/api/utilities/moment"
  to = "/guides/overview/why-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/coverage"
  to = "/guides/tooling/code-coverage"
  status = 301
  force = true

[[redirects]]
  from = "/dashboard-service"
  to = "/guides/cloud/get-started/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/dashboard/overview/runs-dashboard"
  to = "/guides/cloud/features/recorded-runs"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/angular/quickstart"
  to = "/guides/component-testing/angular/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/react/quickstart"
  to = "/guides/component-testing/react/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/svelte/quickstart"
  to = "/guides/component-testing/svelte/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/vue/quickstart"
  to = "/guides/component-testing/vue/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/core-concepts/dashboard-service"
  to = "/guides/cloud/get-started/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/guides/core-concepts/launching-browsers"
  to = "/guides/guides/launching-browsers"
  status = 301
  force = true

[[redirects]]
  from = "/guides/getting-started"
  to = "/guides/getting-started/install-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/install-cypress.md"
  to = "/guides/getting-started/install-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/getting-started/why-cypress"
  to = "guides/overview/why-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/guides/guides/continuous-integration"
  to = "/guides/continuous-integration/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/guides/guides/plugins-guide"
  to = "/api/node-events/overview"
  status = 301
  force = true

[[redirects]]
  from = "/guides/guides/reporters"
  to = "/guides/tooling/reporters"
  status = 301
  force = true

[[redirects]]
  from = "/guides/installing-and-running"
  to = "/guides/getting-started/install-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/guides/references/known-issues"
  to = "/guides/references/trade-offs"
  status = 301
  force = true

[[redirects]]
  from = "/guides/tooling/intelligent-code-completion"
  to = "/guides/tooling/IDE-integration"
  status = 301
  force = true

[[redirects]]
  from = "/guides/web-security"
  to = "/guides/guides/web-security"
  status = 301
  force = true

[[redirects]]
  from = "/intelligent-code-completion"
  to = "/guides/tooling/IDE-integration"
  status = 301
  force = true

[[redirects]]
  from = "/ja"
  to = "/guides/overview/why-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/test-runner"
  to = "/guides/core-concepts/open-mode"
  status = 301
  force = true

[[redirects]]
  from = "/why-cypress"
  to = "/guides/overview/why-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/writeFile"
  to = "/api/commands/writefile"
  status = 301
  force = true

[[redirects]]
  from = "/zh-cn"
  to = "/guides/overview/why-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/zh-cn/guides/getting-started/install-cypress"
  to = "/guides/getting-started/install-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/zh-cn/guides/references/command-line"
  to = "/guides/references/command-line"
  status = 301
  force = true

[[redirects]]
  from = "/zh-cn/guides/guides/module-api"
  to = "/guides/guides/module-api"
  status = 301
  force = true

[[redirects]]
  from = "/zh-cn/guides/overview/why-cypress"
  to = "/guides/overview/why-cypress"
  status = 301
  force = true

[[redirects]]
  from = "/zh-cn/guides/references/assertions"
  to = "/guides/references/assertions"
  status = 301
  force = true

[[redirects]]
  from = "/zh-cn/guides/references/configuration"
  to = "/guides/references/configuration"
  status = 301
  force = true

[[redirects]]
  from = "/guides/references/legacy-configuration"
  to = "/guides/references/configuration"
  status = 301
  force = true

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://docs.cypress.io"
