[build]
  publish = "dist/"
  command = "yarn build"

[context.deploy-preview]
  publish = "dist/"

[[redirects]]
  from = "/"
  to = "/guides/overview/why-cypress/"
  status = 200
  force = true

[[redirects]]
  from = "/guides"
  to = "/guides/overview/why-cypress/"
  status = 301
  force = true

[[redirects]]
  from = "/api"
  to = "/api/table-of-contents/"
  status = 301
  force = true

[[redirects]]
  from = "/api/api/table-of-contents"
  to = "/api/table-of-contents/"
  status = 301
  force = true

[[redirects]]
  from = "/plugins"
  to = "/plugins/directory"
  status = 301
  force = true

[[redirects]]
  from = "/examples"
  to = "/examples/examples/recipes/"
  status = 301
  force = true

[[redirects]]
  from = "/faq"
  to = "/faq/questions/using-cypress-faq/"
  status = 301
  force = true

[[redirects]]
  from = "/guides/dashboard/dashboard-introduction"
  to = "/guides/dashboard/introduction/"
  status = 301
  force = true
	
[[redirects]]
  from = "/guides/component-testing/introduction"
  to = "/guides/overview/choosing-testing-type#What-is-Component-Testing"
  status = 301
  force = true

[[redirects]]
  from = "/guides/component-testing/framework-configuration"
  to = "/guides/getting-started/component-framework-configuration/"
  status = 301
  force = true

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://docs.cypress.io"
