
blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Chat
    url: https://on.cypress.io/discord
    about: Want to discuss Cypress with others? Check out our chat.
  - name: Cypress App or Cloud Issue
    url: https://github.com/cypress-io/cypress-documentation/issues/new
    about: This issue tracker is not for App or Cloud issues. Please open issues related to the App or Cloud here.
